### PR TITLE
Fix sha256 race condition panic

### PR DESCRIPTION
**Pull request by shaodan**

### CODE REVIEW

**Comment by shaodan** [comment]
Create new hmac instance as needed since it is not goroutine safe

**Comment by eynzhang** [comment]
@shaodan , I tried your test code first, I expect it should cause panic but it didn’t. Can you double check that?

And can you explain how you reproduce the issue https://github.com/HuobiRDCenter/huobi_Golang/issues/8 ?

**Comment by shaodan** [comment]
@eynzhang I've fix the panic, so the test should pass. If you want to reproduce that, you need to revert my change of internal/requestbuilder/signer.go

**Comment by eynzhang** [comment]
@shaodan , I didn’t use your code for test. I used your method `TestSigner_Sign_RaceCondition` to test against the master branch, and it passed.

**Comment by shaodan** [comment]
@eynzhang  https://play.golang.org/p/h9_pLX0jieW

**Comment by filinvadim** [comment]
@shaodan @eynzhang Hi folks! Issue was closed but nothing was actually fixed.

**Comment by eynzhang** [comment]
@shaodan thanks for your contribution, your request is merged. I am not sure why I can’t reproduce this issue last time.

**Pull request merged**
